sudo: required
language: node_js
node_js:
    - "9.7.1"
install:
  - npm i
script:
  - npx ng lint
  - npx ng test --watch=false
  - npx ng build --prod
cache:
    directories:
      - node_modules
deploy:
  - provider: pages
    local-dir: dist
    github-token: $github
    skip-cleanup: true
    keep-history: true
notifications:
  slack: $slack
